// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cltypes.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	cltypes.proto
	clservice.proto

It has these top-level messages:
	Client
	OptInt64
	OptString
	Int64Comp
	NewClientRequest
	NewClientResponse
	QueryClientsRequest
	QueryClientsResponse
	GetClientsRequest
	GetClientsResponse
	DeleteClientRequest
	DeleteClientResponse
	DeleteAllClientsRequest
	DeleteAllClientsResponse
	NewMatchRequest
	NewMatchResponse
	SortRequest
	SortResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Birthday int64  `protobuf:"varint,3,opt,name=birthday" json:"birthday,omitempty"`
	Score    int64  `protobuf:"varint,4,opt,name=score" json:"score,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *Client) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type OptInt64 struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *OptInt64) Reset()                    { *m = OptInt64{} }
func (m *OptInt64) String() string            { return proto.CompactTextString(m) }
func (*OptInt64) ProtoMessage()               {}
func (*OptInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OptInt64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type OptString struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *OptString) Reset()                    { *m = OptString{} }
func (m *OptString) String() string            { return proto.CompactTextString(m) }
func (*OptString) ProtoMessage()               {}
func (*OptString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OptString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Int64Comp struct {
	Value int64  `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Op    string `protobuf:"bytes,2,opt,name=op" json:"op,omitempty"`
}

func (m *Int64Comp) Reset()                    { *m = Int64Comp{} }
func (m *Int64Comp) String() string            { return proto.CompactTextString(m) }
func (*Int64Comp) ProtoMessage()               {}
func (*Int64Comp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Int64Comp) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Int64Comp) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "pb.Client")
	proto.RegisterType((*OptInt64)(nil), "pb.OptInt64")
	proto.RegisterType((*OptString)(nil), "pb.OptString")
	proto.RegisterType((*Int64Comp)(nil), "pb.Int64Comp")
}

func init() { proto.RegisterFile("cltypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0xa6, 0x96, 0x66, 0x41, 0x0f, 0x8b, 0x87, 0xe0, 0x29, 0xe6, 0xd4, 0x8b, 0x0d,
	0x52, 0xf5, 0x03, 0xd8, 0x93, 0xa7, 0x42, 0xbc, 0x79, 0x10, 0xf6, 0x1f, 0xe9, 0x40, 0xb2, 0x33,
	0xec, 0x4e, 0x0b, 0xfd, 0xf6, 0xd2, 0x8d, 0x0a, 0x82, 0xb7, 0xf7, 0x76, 0x7f, 0xbc, 0x79, 0x33,
	0xf2, 0xda, 0x8e, 0x7c, 0x26, 0x9f, 0x36, 0x14, 0x91, 0x51, 0x09, 0x32, 0xed, 0xa7, 0x5c, 0xee,
	0x46, 0xf0, 0x81, 0xd5, 0x8d, 0x14, 0xe0, 0xea, 0xa2, 0x29, 0xd6, 0x55, 0x2f, 0xc0, 0x29, 0x25,
	0x17, 0x41, 0x4f, 0xbe, 0x16, 0xf9, 0x25, 0x6b, 0x75, 0x27, 0x57, 0x06, 0x22, 0x1f, 0x9c, 0x3e,
	0xd7, 0x65, 0x53, 0xac, 0xcb, 0xfe, 0xd7, 0xab, 0x5b, 0x79, 0x95, 0x2c, 0x46, 0x5f, 0x2f, 0xf2,
	0xc7, 0x6c, 0xda, 0x46, 0xae, 0xf6, 0xc4, 0x6f, 0x81, 0x5f, 0x9e, 0x2e, 0xc4, 0x49, 0x8f, 0x47,
	0x9f, 0x87, 0x94, 0xfd, 0x6c, 0xda, 0x7b, 0x59, 0xed, 0x89, 0xdf, 0x39, 0x42, 0x18, 0xfe, 0x22,
	0xd5, 0x0f, 0xf2, 0x28, 0xab, 0x9c, 0xb0, 0xc3, 0x89, 0xfe, 0x4f, 0xb9, 0xb4, 0x47, 0xfa, 0xee,
	0x2a, 0x90, 0x5e, 0x9f, 0x3f, 0xb6, 0x03, 0xf0, 0xe1, 0x68, 0x36, 0x16, 0xa7, 0x8e, 0xbc, 0x03,
	0x87, 0xa4, 0x07, 0xec, 0x38, 0x6a, 0x08, 0x10, 0x86, 0x74, 0xb2, 0x0f, 0x36, 0x6f, 0x9e, 0xba,
	0x7c, 0x8e, 0xd4, 0x91, 0x31, 0xcb, 0x2c, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x04,
	0x8a, 0x51, 0x2a, 0x01, 0x00, 0x00,
}
